export const TASKS = [
  {
    id: "laundry",
    name: "Do Your Laundry",
    actionName: "doing laundry",
    color: "#42AAFF",
    emoji: "🧺",
    estimatedTime: "1.5 - 2 hours",
    clorbCount: 103,
    category: "frequent",
  },
  {
    id: "emails",
    name: "Catch Up on Emails",
    actionName: "catching up on emails",
    color: "#49DBC8",
    emoji: "📧",
    estimatedTime: "10-30 minutes",
    clorbCount: 214,
    category: "frequent",
  },
  {
    id: "bed",
    name: "Make Your Bed",
    actionName: "making their bed",
    color: "#FFF172",
    emoji: "🛏️",
    estimatedTime: "2-5 minutes",
    clorbCount: 156,
    category: "frequent",
  },
  {
    id: "dishes",
    name: "Clean the Dishes",
    actionName: "doing dishes",
    color: "#FD9FDD",
    emoji: "🍽️",
    estimatedTime: "5-10 minutes",
    clorbCount: 127,
    category: "frequent",
  },
  {
    id: "sweep",
    name: "Sweep the Floor",
    actionName: "sweeping",
    color: "#FC7339",
    emoji: "🧹",
    estimatedTime: "10-20 minutes",
    clorbCount: 89,
    category: "frequent",
  },
  {
    id: "trash",
    name: "Take Out the Trash",
    actionName: "taking out the trash",
    color: "#AF96FB",
    emoji: "🗑️",
    estimatedTime: "5-10 minutes",
    clorbCount: 41,
    category: "frequent",
  },
  {
    id: "dry",
    name: "Dry the Dishes",
    actionName: "drying dishes",
    color: "#FD9FDD",
    emoji: "🧴",
    estimatedTime: "5-10 minutes",
    clorbCount: 74,
    category: "frequent",
  },
  {
    id: "wipe",
    name: "Wipe Down Surfaces",
    actionName: "wiping surfaces",
    color: "#FFAA00",
    emoji: "🧽",
    estimatedTime: "5-15 minutes",
    clorbCount: 55,
    category: "frequent",
  },
  {
    id: "misc",
    name: "Miscellaneous Chore",
    actionName: "doing a chore",
    color: "#BEFF6C",
    emoji: "✅",
    estimatedTime: "varies",
    clorbCount: 62,
    category: "frequent",
  },
];

export const TASK_CATEGORIES = ["frequent", "kitchen", "bedroom", "office"] as const;

export const CLORB_MESSAGES = [
  "The digital dishes are clean. Are the real ones? I doubt it.",
  "We're all in this together! Sort of.",
  "Doing great! Or are you? Only you know.",
  "Tasks don't do themselves. Unfortunately.",
  "Clorb believes in you. Probably.",
  "Look at all these Clorbs working! Inspiring, right?",
  "You could give up. But where's the fun in that?",
  "Time flies when you're... doing chores?",
  "Remember: Every journey begins with a single sock.",
  "The void appreciates your effort. Kind of.",
  "You're literally doing it right now. Incredible.",
  "Stay strong. The task cannot hurt you.",
];

export type TaskId = (typeof TASKS)[number]["id"];

export function getTaskById(id: string | undefined) {
  return TASKS.find((task) => task.id === id) || TASKS[0];
}
